### ISSUE TITLE
Spectra constructor method

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#10]
Some ideas for the *new* `Spectra` constructor. It should allow to create `Spectra` objects directly from R or alternatively by importing the relevant information from file.

Possibilities:

```r
## Create a Spectra object by all relevant information as a `DataFrame`.
setMethod("Spectra", "DataFrame", function(spectraData, backend, ...) {
    ...
})

## Create a Spectra by reading the data from file(s) passed with parameter `spectraData`
setMethod("Spectra", "character", function(spectraData, backend, ...) {
    ...
})

## Create a Spectra specifying individual columns
setMethod("Spectra", "missing", function(spectraData, backend, msLevel, rt, acquisitionNum,
                    scanIndex, fromFile, centroided, smoothed, polarity, ...))
```

The last method would allow creation of the `Spectra` as with the current `Spectra` constructor: https://github.com/lgatto/Spectra/blob/jomaster/R/Spectra-functions.R#L49-L109

**Comment by sgibb** [comment]
:+1: If we provide different constructors we could move `mzR` from `Depends` to `Suggests`. That would avoid the need for `mzR` for spectra that are not loaded from files.

**Comment by sgibb** [comment]
I should read also the closed issues #6 . Sry.

**Comment by lgatto** [comment]
What are the most sensible use cases to create a `Spectra` object?
1. From raw data files (`MsBackendMzr`)
2. From a single big `DataFrame` (`MsBackendDataFrame`)
These should cover (at least in a first instance) 99% of the cases.

In addition, I could also think of a list of `Spectrum` objects, or an `MSnExp`. But these should be ignored at the moment, as they involve legacy code.

There will be other use cases, such as spectral libraries, but I think we should ignore these for now, and only address them when a specific backend is under consideration. 

Also, some backends, such as `MsBackendHfd5`, is unlikely to have a direct constructor (at least initially) and will rather be initialised by switching from another backend.

Finally, I think that a function like `readMSData()` reading data from raw files should still be prioritised for most users.

**Comment by jorainer** [comment]
I agree. 1) and 2) should cover most cases. 

Another use case I will have pretty soon is to create a `Spectra` from a `CompoundDb` (i.e. a database that contains MSMS spectra). I'd then like to have a method `setMethod("Spectra", "CompDb", ...)` that returns a `Spectra` with a dedicated backend for the `CompDb` to retrieve/query the spectra from the database and enable matching of spectra against that.

**Comment by jorainer** [comment]
PR https://github.com/lgatto/Spectra/pull/22 has 2 constructor methods for `Spectra`:
- from a `DataFrame` that contains all the spectra data
- from a `MsBackend`
Seems to work nicely.
