### ISSUE TITLE
CI: travis or GHA

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#105]
We currently use travis and GitHub actions. I suggest we drop the former. 

@sgibb @jorainer

**Comment by jorainer** [comment]
Absolutely. And we then also enable the packagedown step in the github action.

**Comment by lgatto** [comment]
Ah, that isn't in yet (good I asked before breaking it). Feel free to send a PR, otherwise I will look into another repo to learn how to do it.

**Comment by jorainer** [comment]
Also pkgdown works with GA. Closing issue.

**Comment by lgatto** [comment]
I have disabled `Spectra` on travis - it seemed to still be build despite the lack of config file.
