### ISSUE TITLE
Convert MSnbase::Spectrum2 <-> Spectra object

### ISSUE THREAD

**Issue by korseby** [rformassspectrometry/Spectra#123]
Hi,

this is a simple feature request. Or maybe I have overseen it?

I would like to convert from and to `Spectrum2`-objects from `MSnbase`... 

Best wishes, *Kristian

**Comment by jorainer** [comment]
good point - but there is also the question into which package this function should go - I don't want to add `MSnbase` as a dependency to `Spectra` (in case the function goes into `Spectra`), but also the other way round is not ideal.

**Comment by jorainer** [comment]
In fact, I have a small utility function that can extract the data from an `MSnExp` or `list` of `MSnbase::Spectrum` objects to put that into a `Spectra::Spectra` object [extractSpectraData](https://euracbiomedicalresearch.github.io/CompMetaboTools/reference/extractSpectraData.html). In case you don't want to install that whole [CompMetaboTools](https://github.com/EuracBiomedicalResearch/CompMetaboTools) (it's just a collection of functions we frequently use in our group) you can also simply use the function without the package (or implement one yourself) - it's very simple:

```r
#' @title Extract data from MSnbase objects for use in Spectra
#'
#' @description
#'
#' `extractSpectraData` extracts the spectra data (m/z and intensity values
#' including metadata) from [MSnbase::Spectrum1] or [MSnbase::Spectrum2] objects
#' (or `list` of such objects) and returns these as a `DataFrame` that can
#' be used to create a [Spectra::Spectra] object. This function enables thus
#' to convert data from the *old* `MSnbase` package to the newer `Spectra`
#' package.
#'
#' @param x a `list` of [MSnbase::Spectrum] objects or an object extending
#'     [MSnbase::MSnExp] (such as also the [xcms::XCMSnExp] object).
#'
#' @return [S4Vectors::DataFrame] with the full spectrum data that can be
#'     passed along to the [Spectra::Spectra()] function to create such an
#'     object.
#'
#' @author Johannes Rainer
#'
#' @export
#' 
#' @importFrom S4Vectors DataFrame
#'
#' @importFrom IRanges NumericList
#'
#' @importFrom methods is
#' 
#' @examples
#'
#' ## Read an mzML file with MSnbase
#' fl <- system.file("TripleTOF-SWATH", "PestMix1_SWATH.mzML",
#'     package = "msdata")
#' data <- MSnbase::filterRt(MSnbase::readMSData(fl, mode = "onDisk"),
#'     rt = c(1, 6))
#'
#' ## Extract the data as a DataFrame
#' res <- extractSpectraData(data)
#'
#' ## This can be used as an input for the Spectra constructor of the
#' ## Spectra package.
#' sps <- Spectra::Spectra(res)
#' sps
extractSpectraData <- function(x) {
    if (is(x, "list")) {
        df <- DataFrame(do.call(rbind, lapply(x, MSnbase:::.spectrum_header)))
        df$mz <- NumericList(lapply(x, function(z) z@mz))
        df$intensity <- NumericList(lapply(x, function(z) z@intensity))
    } else if (inherits(x, "MSnExp")) {
        df <- DataFrame(MSnbase::fData(x))
        df$mz <- NumericList(MSnbase::mz(x))
        df$intensity <- NumericList(MSnbase::intensity(x))
    } else stop("'x' should be either a 'list' of 'Spectrum' objects or an ",
                "object extending 'MSnExp'")
    df
}
```

the way back would be more difficult - and slower.

**Comment by korseby** [comment]
Hm... I tried to convert it but it does not work.

What kind of object do I have here in my example?

```R
> typeof(feat_spectra_pos[[1]]@listData[[1]])
[1] "S4"
> feat_spectra_pos[[1]]@listData[[1]]
Object of class "Spectrum2"
 Precursor:  
 Retention time: 2:33 
 Charge:  
 MSn level: 2 
 Peaks count: 3 
 Total ion count: 2562.068 
> is(feat_spectra_pos[[1]]@listData[[1]])
[1] "Spectrum2" "Spectrum"  "Versioned"
```

I discovered that the `MSnbase::writeMgfData` function is very rudimentary and does not write all headers... So it would be nice to use the new `Spectra` object for that. Just as a side note what I'm trying to accomplish. ;)

Many greetings

**Comment by jorainer** [comment]
Can you just call `class(feat_spectra_pos)`? Could be that it is a `MSnbase::MSpectra` object (which is also simply a `list`).

Re MGF data - AFAIK there is somebody working on a MGF backend for `Spectra` so that you can import/export data from/to MGF files but I don't know how much is already implemented.

**Comment by jorainer** [comment]
This newer version of the function (I've also updated the `CompMetaboTools` package) should also work with `MSnbase::MSpectra` objects:

```r
extractSpectraData <- function(x) {
    if (inherits(x, "MSpectra")) {
        df <- DataFrame(do.call(rbind, lapply(x, MSnbase:::.spectrum_header)))
        df <- cbind(df, MSnbase::mcols(x))
        df$mz <- NumericList(lapply(x, function(z) z@mz))
        df$intensity <- NumericList(lapply(x, function(z) z@intensity))
    } else if (is(x, "list") || inherits(x, "SimpleList")) {
        df <- DataFrame(do.call(rbind, lapply(x, MSnbase:::.spectrum_header)))
        df$mz <- NumericList(lapply(x, function(z) z@mz))
        df$intensity <- NumericList(lapply(x, function(z) z@intensity))
    } else if (inherits(x, "MSnExp")) {
        df <- DataFrame(MSnbase::fData(x))
        df$mz <- NumericList(MSnbase::mz(x))
        df$intensity <- NumericList(MSnbase::intensity(x))
    } else stop("'x' should be either a 'list' of 'Spectrum' objects or an ",
                "object extending 'MSnExp' or 'MSpectra'.")
    df
}
```

**Comment by sgibb** [comment]
I guess we could add this function to `MSnbase` as `as.data.frame` (or `as.DataFrame`) or `as(x, "DataFrame")`, or? It would not add any dependencies. IMHO it is nice to allow easy conversion from `MSnbase` to `Spectra` but I don't think we have to provide the other way because `Spectra` should replace the `MSpectra` class in the long run.
(Or a simple `as(x, "MSpectra")` where `x` is a `DataFrame` could do the job.)

**Comment by jorainer** [comment]
Totally agree - but it might be confusing to the user: we have a `as.data.frame.MSnExp` and a `as(x, "data.frame")`: these return a `data.frame` with columns `"file"`, `"rt"`, `"mz"` and `"intensity"`, one row per peak. What we want is a `DataFrame`, one row **per spectrum** with all the spectra variables in it.
So maybe simply add the function there? With its current name `extractSpectraData` to distinguish it from the ones above?

**Comment by korseby** [comment]
Hi,

great to see the movement here. 👍 

My object looks like this:

```R
> class(feat_spectra_pos)
[1] "list"
> class(feat_spectra_pos[[1]]@listData[[1]])
[1] "Spectrum2"
attr(,"package")
[1] "MSnbase"
> inherits(x, "Spectrum2")
[1] TRUE
```

The new function also does not work. 

When converted, what about additional information like which instrument was used, adduction mode, ... ? How can we get this information into the object? I'm asking because I'd like to use the object to write a MGF and/or MSP converter sometime in the future.

**Comment by jorainer** [comment]
Hm, could you provide the actual error message you get? This *should* work in principle (maybe you need to call also `library(IRanges)` before the call).

Once you have the `Spectra` you can add arbitrary new columns to it: `sps$new_column <- value` would add a new *column*/spectra variable `"new_column"` to your `Spectra` object `sps` with `value` being either of length 1 or length equal `length(sps)`. This allows to add arbitrary annotations to each individual spectrum (each element/*row* in `sps` is one spectrum). And the good news is that we will add a function to export a `Spectra` object to mgf (issue #124) - so we will involve you in the discussion regarding additional header elements etc.

**Comment by korseby** [comment]
Hm... Maybe I'm overseeing something?

```R
> x<-feat_spectra_pos[[1]]@listData[[1]]
> class(x)
[1] "Spectrum2"
attr(,"package")
[1] "MSnbase"
> inherits(x, "Spectrum2")
[1] TRUE
> DataFrame(do.call(rbind, lapply(x, MSnbase:::.spectrum_header)))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': no method for coercing this S4 class to a vector
> DataFrame(MSnbase::fData(x))
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'fData' for signature '"Spectrum2"'
```

**Comment by jorainer** [comment]
What happens if you call `extractSpectraData(feat_spectra_pos)`?

**Comment by korseby** [comment]
That's what happens:

```R
> extractSpectraData(feat_spectra_pos)
 Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': 'list' object cannot be coerced to type 'double' 
> class(feat_spectra_pos)
[1] "list"
> str(feat_spectra_pos, max.level = 1)
List of 4852
 $ FT0001:Formal class 'Spectra' [package "MSnbase"] with 4 slots
 $       : list()
 $       : list()
 $ FT0004:Formal class 'Spectra' [package "MSnbase"] with 4 slots
 $ FT0005:Formal class 'Spectra' [package "MSnbase"] with 4 slots
 $ FT0006:Formal class 'Spectra' [package "MSnbase"] with 4 slots
 $       : list()
 $ FT0008:Formal class 'Spectra' [package "MSnbase"] with 4 slots
....
```

That's part of my SWATH processing. `feat_spectra_pos` is a list of Spectra2 objects which are generated by XCMS.

```R
swath_spectra_pos <- reconstructChromPeakSpectra(swath_data_pos, minCor=0.5)

# Grab "spectra of interest"
feat_spectra <- swath_spectra_pos[which(mcols(swath_spectra_pos)$peak_id %in% rownames(feat_ms2_list))]

# Merge spectra
feat_spectra_merged <- combineSpectra(feat_spectra, mzd=0.05, ppm=50, intensityFun="max")

# Append "spectrum of interest" to list		
feat_spectra_pos[[i]] <- feat_spectra_merged
```

**Comment by jorainer** [comment]
OK, so it's a `list` of `Spectra` objects then.

```r
res <- lapply(feat_spectra_pos, extractSpectraData)
```

should work

**Comment by korseby** [comment]
Hm....

```R
> res <- lapply(feat_spectra_pos, extractSpectraData)
 Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'args' in selecting a method for function 'do.call': arguments imply differing number of rows: 0, 1 
14.
h(simpleError(msg, call)) 
13.
.handleSimpleError(function (cond) 
.Internal(C_tryCatchHelper(addr, 1L, cond)), "arguments imply differing number of rows: 0, 1", 
    base::quote(data.frame(acquisitionNum = acquisitionNum(x), 
        msLevel = msLevel(x), polarity = polarity(x), peaksCount = peaksCount(x),  ... 
12.
stop(gettextf("arguments imply differing number of rows: %s", 
    paste(unique(nrows), collapse = ", ")), domain = NA) 
11.
data.frame(acquisitionNum = acquisitionNum(x), msLevel = msLevel(x), 
    polarity = polarity(x), peaksCount = peaksCount(x), totIonCurrent = tic(x), 
    retentionTime = rtime(x), basePeakMZ = mz(x)[which.max(intensity(x))][1], 
    basePeakIntensity = max(intensity(x)), collisionEnergy = NA_real_,  ... 
10.
FUN(X[[i]], ...) 
9.
lapply(as.list(X), match.fun(FUN), ...) 
8.
lapply(as.list(X), match.fun(FUN), ...) 
7.
lapply(x, MSnbase:::.spectrum_header) 
6.
lapply(x, MSnbase:::.spectrum_header) 
5.
do.call(rbind, lapply(x, MSnbase:::.spectrum_header)) 
4.
DataFrame(do.call(rbind, lapply(x, MSnbase:::.spectrum_header))) 
3.
FUN(X[[i]], ...) 
2.
lapply(feat_spectra_pos, extractSpectraData) 
1.
lapply(feat_spectra_pos, extractSpectraData) 
```

**Comment by jorainer** [comment]
and how about `extractSpectraData(feat_spectra_pos[[1]])`?

**Comment by jorainer** [comment]
If that doesn't work, could you eventually share this one object with me (-> email)?

**Comment by korseby** [comment]
You've got an email. ;)

**Comment by meowcat** [comment]
> 
> 
> good point - but there is also the question into which package this function should go - I don't want to add `MSnbase` as a dependency to `Spectra` (in case the function goes into `Spectra`), but also the other way round is not ideal.

Conceptually one could also do a MsBackendMSnbase to import from legacy objects?

**Comment by lgatto** [comment]
Closing for now. Feel free to reopen if necessary.
