### ISSUE TITLE
New export method

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#124]
- Serialise any `Spectra` object to mgf.
- Also (later) serialise to mzML.

**Comment by jorainer** [comment]
We may rethink the concept of exporting the data eventually by adding an `MsBackend,export` method. Tagging @michaelwitting @meowcat @sgibb and @lgatto

**Comment by jorainer** [comment]
Note that a simple dispatching of the `export,Spectra` to `export,MsBackend` will **not** work, because the backend does not know anything about data manipulations that have been happening in the `Spectra` object (i.e. that are in the processing queue).

**Comment by jorainer** [comment]
So, IMHO the best would be to have a `export,MsBackend` method that takes a `Spectra` object as input. The definition of the `export` could be:

```r
setMethod("export", "Spectra", "MsBackend", function(object, backend, file, ...) {
    ## use here the `spectraData` method to get all metadata of the Spectra
    ## and the `as.list` to get the peaks (m/z and intensity values)
})
```

and this function should be defined in the package providing the backend (e.g. `MsBackendMgf`). I will tinker a little with this in the `MsBackenMgf` package to see if that works or if there is some unforseen problem with it.

**Comment by lgatto** [comment]
I thought that `export,MsBackend` had always been on the table (but maybe I'm confused with `reset`).

Why could `export,Spectra` not call `export,MsBackend` **after** somehow handling the delayed processing/filtering operations? I am not keen on `export,MsBackend` hanlding a `Spectra` object. I think the devil is in the details here, in particular on the type of  on-disk backend.

**Comment by jorainer** [comment]
I know, it doesn't sound intuitive that the backend should deal with a `Spectra`. 

Your suggestion with handling the processing queue would however mean to use `applyProcessing` on the `Spectra`, which replaces peak values in the backend, something that read-only backends, such as the `MsBackendMzR` would not support. The alternative would be to call `.peaksapply` in the `export,Spectra` and pass then this `list` of peak matrices to the `export,MsBackend` - so we would have in the worst case have twice the peak data in memory - I would like to avoid that, also to support large scale mzML-based experiments. 

IMHO it would be an easier and cleaner implementation if we passed the `Spectra` object to the backend - in the simple case the backend export method has to simply call the `spectraData` and `as.list` methods on the `Spectra`, but we would also allow for other implementations, such as for `MsBackendMzR` where I would like to perform the export on a per-file basis and would only load the data from one file at a time to be more memory efficient.

**Comment by lgatto** [comment]
This looks sensible. It would be good to discuss this during a call, and pencil the different use cases out:
- `export,MsBackendMgf` writes all spectra to a single mgf file.
- `export,MsBackendMzR` writes spectra in *n* mzML files, based by default on `dataOrigin, but could be controlled by the user.
- ...

And I think we should also think about **serialising the `Spectra` objects themselves** to be able to use these potentially very large objects across different sessions.

**Comment by jorainer** [comment]
Re call, today I have a call only from 10-11 and would be available all the other time.

Re the different use cases:
- I would keep it to the developer of the backend to decide how to handle multi-file support. For mgf, for now, we export only to a single file. For `MsBackendMzR` I would do it by default on a per-file basis (using the `dataStorage` of the backend) - thus the user has to provide `file` that has length equal to `length(unique(sps$dataStorage))`. Implementation should be simple: split the `Spectra` by `dataStorage` and export each file separately (in parallel) - this would also keep memory requirements low.

Re serializing: should work out-of-the-box for most backends - except database-based ones, since serializing the database connection might not work.

**Comment by jorainer** [comment]
All this code is at present in the *jomaster* branch - I will make a PR once the Bioc submission is through.

**Comment by lgatto** [comment]
Can't remember if this has been merged yet?

**Comment by jorainer** [comment]
Yep. You just merged that.
