### ISSUE TITLE
Peaks and spectra data accessors and replacement methods

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#128]
Discussion stemming from the package review:
- keep `as(Spectra, "SimpleList")` and `as(Spectra, "list")` - these would call `peaksData,MsBackend`. The `setAs` method would be the preferred way to access the peaks as a list. 
- keep `spectraData()`  and drop all `asDataFrame`, `as(...)` ... because we can't use additional arguments (`spectraVariables = ...)`, for `Spectra` and `MsBackend`
-  also have a `peaksData` that does the same as `as(Spectra, "SimpleList")` - and also a method for the backends. This method is added so that we can have a clean name and syntax for the replacement method (see below)
And for the replacement methods:
- `spectraData<-,MsBackend`
- `peaksData<-,MsBackend`

Related issue: #86

**Comment by jorainer** [comment]
All has been implemented now and was pushed also to BioC. Now lets wait for Marcel's reply.
