### ISSUE TITLE
Implement MsBackendHdf5

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#13]
Implement the backend using the Hdf5 backend.

**Comment by jorainer** [comment]
Low level Hdf5 data access functions could be taken directly from https://github.com/lgatto/MSnbase/blob/backends_jo/R/BackendHdf5-class.R

**Comment by jorainer** [comment]
Is somebody working on this? @lgatto ? @sgibb ?

**Comment by lgatto** [comment]
I am waiting to do anything before we iron out some open questions with `MsBackendDataFrame`. I prefer to wait to set the details in stone with the API and this simpler use case before implementing anything.

**Comment by jorainer** [comment]
Am currently working on a simple implementation that keeps m/z and intensity values in an HDF5 while keeping the other spectra variables in memory (much like the `MsBackendMzR`).
