### ISSUE TITLE
Add a chapter about backends in vignette

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#14]
Once the API is defined, we need a new section in the MSnbase development vignette that describes backends (pointing the the manual with a more detailed definition of the API) and provides an example of how to write a new backend.

**Edit** this issue was initially opened in `MSnbase` but has been transferred here, given that the Spectra and backends infrastructures got their own packages.

**Comment by jorainer** [comment]
Closing because I've added an `MsBackend` section to the vignette. Feel free to re-open if it's not descriptive/comprehensive enough.
