### ISSUE TITLE
Export the mzXML?

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#151]
The documentation says

> - `MsBackendMzR` (`Spectra` package): export data in *mzML* and *mzXML*

although I was under the impression only `mzML` was supported in effect, even though `mzXML` is supported by pwiz. 

1. Can `mzR` et thus `Spectra` export to `mzXML`?
2. If so, how?

**Comment by jorainer** [comment]
Sure, `mzR` can write *mzXML* files too. To export a `Spectra` in *mzXML* format:

```r
export(sps, backend = MsBackendMzR(), file = "outfile.mzXML", format = "mzXML")
```

**Comment by lgatto** [comment]
Thank you!
