### ISSUE TITLE
addFragments [was splotSpectraWithFragments()]

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#155]
We are missing a function that plot an MS2 spectrum and annotates it's fragment peaks. I have implemented such a [function](https://github.com/rformassspectrometry/PSM/blob/main/R/plotSpectraWithFragments.R) in the `PSM` package:

```r
> sp
MSn data (Spectra) with 1 spectra in a MsBackendDataFrame backend:
    msLevel     rtime scanIndex
  <integer> <numeric> <integer>
1         2      2345        NA
 ... 17 more variables/columns.
> sp$sequence
[1] "SIGFEGDSIGR"
> plotSpectraWithFragments(sp, sp$sequence, labelPos = 3)
```

![Rplot001](https://user-images.githubusercontent.com/384198/97562893-a23ad500-19e2-11eb-949a-176b8c5d8a02.png)

This function is in `PSM` because it needs the `PSM::calculateFragments()` (ported from `MSnbase`). 

I suggest to 
1. Submit `PSM` asap to Bioconductor
2. Then transfer `splotSpectraWithFragments()` to `Spectra` and improve it (to for example work with more spectra).

@jorainer @sgibb - ok for you?

**Comment by jorainer** [comment]
I'm just wondering (and maybe it's not possible) - wouldn't it be better to implement only an e.g. `labelFragments` function that can be passed with the parameter `labels`?

**Comment by lgatto** [comment]
That's a really good idea, especially it would be able to pass it to all other plotting functions. 

That function would need the access to the peaks, available in the `splotSpectra()` and the peptide sequence, and would need to do the matching and return labels. That might make it difficult when when plotting many spectra, unless it is provided with the spectra variables containing the peptide sequence. Something like

```r
plotSpectra(ms, labels = addFragments("sequence"))
```

where `"sequence"` refers to `ms$sequence`

Such a function would however not be able to colour the matching peaks. I'm unsure if this is an important requirement.

**Comment by jorainer** [comment]
That's how I used a label function: `adds` is a named numeric vector where the values are theoretical m/z of adducts for a certain compound and the names being the adduct name (e.g. `"[M+H]+"`). The `label_fun` is then simply comparing the m/z values of `adds` with those of the peaks and if the difference is acceptable small it returns the name of the adduct - which is then used as label (`sps` is a single spectrum `Spectra` in this case):

```r
label_function <- function(x) {
    names(adds)[MsCoreUtils::closest(mz(x)[[1L]], adds,
                                     tolerance = 0, ppm = 40,
                                     duplicates = "closest")]
}
plotSpectra(sps, labels = label_function, labelPos = 3, labelSrt = 45)
```

The result:
![Untitled](https://user-images.githubusercontent.com/5506112/97577819-3495a580-19f0-11eb-964f-2dfff67244d1.png)

**Comment by lgatto** [comment]
This seems to work, which would be my preferred solution. 
```r
addFragments <- function(x, y = "sequence",
                         tolerance = 0,
                         ppm = 20) {
    stopifnot(inherits(x, "Spectra"),
              length(x) == 1)
    stopifnot(y %in% spectraVariables(x))
    y <- spectraData(x)[[y]]

    ## Prepare x and y data
    x_data <- Spectra::peaksData(x)[[1L]]
    y_data <- calculateFragments(y, verbose = FALSE)
    y_data <- y_data[order(y_data$mz), ]

    ## Find common peaks and prepare annotations
    idx <- which(MsCoreUtils::common(x_data[, "mz"], y_data[, "mz"],
                                     tolerance = tolerance, ppm = ppm))
    idy <- which(MsCoreUtils::common(y_data[, "mz"], x_data[, "mz"],
                                     tolerance = tolerance, ppm = ppm))

    ## Prepare labels
    labels <- rep(NA_character_, nrow(x_data))
    labels[idx] <- y_data[idy, "ion"]
    labels    
}
```
Will do some more testing before pushing to `PSM`.

**Comment by lgatto** [comment]
Only thing that doesn't seem to work is passing a different spectra variable (the y = "sequence" above). I would be fine with requireing a `"sequence"` in the `spectraData(x)`. @jorainer ?

**Comment by lgatto** [comment]
There is now a `PSM::addFragments()` function and `splotSpectraWithFragments()` has been removed.

**Comment by jorainer** [comment]
> Only thing that doesn't seem to work is passing a different spectra variable (the y = "sequence" above). I would be fine with requireing a "sequence" in the spectraData(x).

Can you please elaborate on this @lgatto ?

**Comment by lgatto** [comment]
The [following](https://github.com/rformassspectrometry/PSM/blob/main/R/addFragments.R#L63-L87) works as expected:
```r
plotSpectra(x, label = addFragments)
```
It however expects that `x` has a [spectra variable named `sequence`](https://github.com/rformassspectrometry/PSM/blob/main/R/addFragments.R#L69). 

What I haven't managed to do is for the user to specify the spectra variable, something like:
```r
plotSpectra(x, label = addFragments(sequence = "pepseq"))
```
where `sequence` would be an argument of `addFragments`.

I'm not sure I would want to add a `sequence` argument to the `plotSpectra` *et al.* functions:
```r
plotSpectra(x, label = addFragments, sequence = "pepseq")
```
