### ISSUE TITLE
Fix github actions

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#161]
We still have errors with the github actions, which is very strange as I don't have these problems when I run the checks locally (using the same docker images).

**Comment by jorainer** [comment]
No idea why the tests are failing. Seems like a problem with `vdiffr` and an issue with files that can not be found.

**Comment by jorainer** [comment]
For now I disabled `vdiffr` in the GH action - for some odd reasons `vdiffr` fails although locally (using the same docker image as well as using the mac R version) it works.

**Comment by jorainer** [comment]
Windows version seems to be fixed. Problem is the macos version - seems because of compiler problems

**Comment by lgatto** [comment]
Can't we close this now?
