### ISSUE TITLE
passing additional parameters to filterIntensity

### ISSUE THREAD

**Issue by ococrook** [rformassspectrometry/Spectra#164]
The vignette suggest you can pass a function to "filterIntensity" which is great. Though ?filterIntensity doesn't seem to have any example at the moment but I'm sure there was one before which inspired my question

I would like to filter out low_intensities, this works exactly as intended

```{r,}
# function to filter out intensity smaller than the 5% of max intensity
low_int <- function(x, percentage = 0.05) {
  x > max(x, na.rm = TRUE) * percentage
}

filterIntensity(mySpectraObject, low_int) 
```
Now I might want my intensity filtering to be adaptive and so passing a value to low_int without recreating the function. That is it would be nice to be able to pass additional arguments to that function ...

```{r,}
filterIntensity(mySpectraObject, low_int, percentage = 0.01)
```
or 

```{r,}
filterIntensity(mySpectraObect, low_int, methargs = list(percentage = 0.01))
```

Might be too much effort, but would be useful personally

**Comment by jorainer** [comment]
This has now also been added to the BioC 3.12 version of Spectra. Please close the issue if it works for you @ococrook
