### ISSUE TITLE
pickPeaks missing ...

### ISSUE THREAD

**Issue by ococrook** [rformassspectrometry/Spectra#168]
I think the method for pickPeaks is missing a `...` argument

I would expect `span = 0.2` to be passed to the function `noise`

```{r,}
peaksMethod = "SuperSmoother"
snr <- 2
object_sub <- Spectra::pickPeaks(object_sub,
                                 method = peaksMethod,
                                 halfWindowSize = halfWindowSize,
                                 snr = snr, k = 0L, descending = FALSE, threshold = 0, msLevel = 1, span = 0.2)
```
Error in .local(object, ...) : unused argument (span = 0.2)

**Comment by jorainer** [comment]
Thanks for reporting! (and sorry for the delay) - I'll look into this.

**Comment by jorainer** [comment]
Version 1.1.11 fixes this. Please close the issue after veryfying that it works for you.

**Comment by ococrook** [comment]
This works for me, thanks!
