### ISSUE TITLE
Show method for Spectra too long

### ISSUE THREAD

**Issue by ococrook** [rformassspectrometry/Spectra#173]
Hi @jorainer 

The `show` for the spectra currently shows the processing slot for the object. This is great, but after you've processed a large amount of data this can be a few thousand lines long and just eats the console when printed. Do you think it would be sensible to keep the max number of lines printed to say 10?

**Comment by jorainer** [comment]
I agree. I'll implement that.

**Comment by ococrook** [comment]
Thanks :)

**Comment by jorainer** [comment]
This is now implemented in the current devel version. Install with `BiocManager::install("rformassspectrometry/Spectra")`.

I'm closing the issue now, feel free to re-open if needed.

**Comment by ococrook** [comment]
Thanks :)
