### ISSUE TITLE
Should we have a uniqueMsLevel() accessor

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#191]
For some (large) datasets, calculating the unique MS levels can be tricky. For example, in the signature of `filterRt()` we have `unique(msLevel(object))` which would become inefficient for an on-disk backend with large data. 

There's such an implementation for the SQLite backend [here](https://github.com/plantton/MsBackendSql/blob/master/R/MsBackendSqlDb-functions.R#L574-L591), and I was wondering of we might not need to generalise this?

**Comment by jorainer** [comment]
sounds good to me - no objections against a `uniqueMsLevel` method defined for `MsBackend`. The one for `MsBackend` could essentially just `unique(msLevel(object))` and each backend can implement its own if needed.

What I was however puzzled in the SQLite backend implementation was the need of a temporary table - wouldn't a simple `select distinct... where _pkey = ` suffice there?

**Comment by lgatto** [comment]
Ping @plantton

**Comment by plantton** [comment]
> sounds good to me - no objections against a `uniqueMsLevel` method defined for `MsBackend`. The one for `MsBackend` could essentially just `unique(msLevel(object))` and each backend can implement its own if needed.
> 
> What I was however puzzled in the SQLite backend implementation was the need of a temporary table - wouldn't a simple `select distinct... where _pkey = ` suffice there?

The issue is that the key word `distinct` again doesn't work with `dbBind` + prepared statements. I will reproduce an example with `MsBackendSql` backend.

**Comment by jorainer** [comment]
OMG, now that's really a bummer. Good that you found this @plantton . Would something like

```r
dbGetQuery(b1@dbcon, paste0("select distinct msLevel from msdata where _pkey in (", paste(b1@rows, collapse = ","),")"))
```

also work? I am OK with the temporary table, I just find it a little complicated (and eventually slower?)

**Comment by plantton** [comment]
I had a benchmark about the similar issue. Three functions are compared here: 
- Method A: `SELECT _pkey, filterString FROM msdata`, and the slot `rows` are passed by `dbBind` as prepared statement. While `filterString` are passed as `paste(str, collapse = "', '")`.
- Method B: Similar to A, but slot `rows` are passed as `paste(rows, collapse = ", ")`. 
- Method C: Use `TEMPORARY TABLE` and table join to finish the task.

Method B is indeed faster than the other approaches.  
![image](https://user-images.githubusercontent.com/3836388/113122014-83e83800-9213-11eb-8968-6cded3197d8c.png)

But the critical issue of Method B is the peak RAM usage.
![image](https://user-images.githubusercontent.com/3836388/113121297-c9f0cc00-9212-11eb-9421-2cde702a588a.png)

To find out the RAM consumption on a huge dataset, I made a linear regression to estimate the RAM usage of using Method B on the a dataset with 42592313 spectrum/rows. The final RAM consumption would be 1460.965 MiB.

![image](https://user-images.githubusercontent.com/3836388/113122471-f48f5480-9213-11eb-90f9-67c0662e75f2.png)

There is a trade-off between velocity and RAM consumption. When it's impossible to use a few SQL keywords with `dbBind`, the better solution is to use the `TEMP TABLE`.

**Comment by jorainer** [comment]
Nice comparison! Thanks @plantton ! This huge memory requirement is somewhat strange. It must be the related to the concatenation of the primary keys... Could you please check what the `peakRAM` of the `paste0` call on the primary keys is? Just to understand where this memory requirement comes from...

**Comment by plantton** [comment]
I think the concatenated integers are the reason. I tested both `paste0` and `paste` methods:

```R
demoRows <- seq(5)
s0 <- paste0(demoRows, collapse = ", ")
s1 <- paste(demoRows, collapse = ", ", sep = " ")
```
Then just use `peakRAM` to capture the RAM consumptions for the 2 methods.

![image](https://user-images.githubusercontent.com/3836388/113166671-49968f00-9243-11eb-83f1-9138a6199b43.png)

For a dataset with 42592313 spectrum, the RAM consumption of `paste0` is 1133 MiB.

![image](https://user-images.githubusercontent.com/3836388/113167210-caee2180-9243-11eb-89a2-4ddf4d91f753.png)


While the RAM consumption of `paste` is 970 MiB.

![image](https://user-images.githubusercontent.com/3836388/113167281-dd685b00-9243-11eb-8ec1-c437ebe6fcbf.png)

And the RAM usage can be tested by another way:

```R
ls1 <- list(seq(20000), seq(100000), seq(200000),
            seq(1000000), seq(4000000), seq(9000000))
object_size(paste(ls1[[6]], collapse = ", ", sep = " "))
## 79.9 MB
```
So it's not surprised to find the big dataset would use 1 Gb of RAM for the filter function.

**Comment by lgatto** [comment]
new generic added to ProtGenerics 1.23.9

**Comment by plantton** [comment]
> ProtGenerics 1.23.9

Import in a [new commit ](https://github.com/plantton/MsBackendSql/commit/ec66c12d43556782b6b6246fa2144ef20917c893)
