### ISSUE TITLE
Warning issue of setBackend

### ISSUE THREAD

**Issue by plantton** [rformassspectrometry/Spectra#217]
Example:

```R
fls <- dir(system.file("sciex", package = "msdata"), full.names = TRUE)

sps <- Spectra(fls, backend = MsBackendDataFrame())
sps <- setBackend(sps, MsBackendMzR())
#> Error in .local(object, backend, ...): MsBackendDataFrame is read-only. Changing backend to a read-only backend is not supported.
```
It's more appropriate to say "MsBackendMzR is read-only". Just replace:  
[stop(backend_class, " is read-only. Changing backend to a ",](https://github.com/rformassspectrometry/Spectra/blob/master/R/Spectra.R#L1232)  

With  
```R
stop(class(backend), " is read-only. Changing backend to a ",
```

**Comment by jorainer** [comment]
Thanks for reporting! I've fixed this now in the devel and release branch.
