### ISSUE TITLE
compareSpectra to always (by default) return a matrix

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#219]
Add a `drop = FALSE` parameter to `compareSpectra` so that results are always returned as a `matrix` even if the number of query or target spectra is 1. (see https://github.com/jorainer/SpectraTutorials/issues/27 for reference).

**Comment by sgibb** [comment]
Don't we have a `SIMPLIFY` argument already? Isn't it working with `SIMPLIFY = FALSE`? Maybe we should change the default or drop this argument at all?
