### ISSUE TITLE
Create neutralLoss spectra

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#236]
Add a function `neutralLoss` to create *neutral loss* spectra versions of a `Spectra`. The function could be defined in the following way:

```r
neutralLoss(x, msLevel. = 2L, peaks = c("all", "bigger", "smaller")) {
}
```

With `x` being a `Spectra`, `msLevel.` to define the MS level on which to perform the calculation (MS2 would make most sense obviously) and `peaks` allowing to define in addition if peaks should be pre-filtered:

- `peaks = "all"`: report all fragment peaks.
- `peaks = "bigger"`: only report fragment peaks with an m/z > precursor m/z.
- `peaks = "smaller"`: only report fragment peaks with an m/z < precursor m/z.

Any feedback and suggestions welcome @michaelwitting

**Comment by jorainer** [comment]
I checked the (php) code of https://doi.org/10.1021/jasms.1c00343 (available [here](https://github.com/masspec/MS2ToNLConverter)). Seems they are simply calculating `precursor m/z - fragment m/z` and report the intensity of the fragment peak. No additional filtering is done. Also, no special handling of negative m/z values etc is performed.

**Comment by jorainer** [comment]
Maybe better to have a parameter `filterPeaks = c("none", "largerPmz")` that also supports a user-specified `function` to filter the peaks matrix. `"largerPmz"` would remove all peaks with an m/z that is larger than the one from the precursor m/z (`"Pmz"`).

**Comment by sgibb** [comment]
Maybe you could reuse code from here: https://github.com/lgatto/MSnbase/blob/master/R/functions-fragments.R
(it is already reused/copied to `PSMatch`: https://github.com/rformassspectrometry/PSMatch/blob/main/R/fragments-calculate.R)

**Comment by jorainer** [comment]
Seems that type of neutral loss calculations are different than the one I had in mind (i.e. the neutral loss spectra from https://doi.org/10.1021/jasms.1c00343 that are defined as precursor m/z - fragment m/z and the *hypothetical neutral loss* from https://doi.org/10.1021/acs.analchem.0c02521). 

Considering that, it would maybe be better to define `neutralLoss` as a method for `Spectra` that dispatches on a `Param` object which also defines the type of calculation that should be performed:

- `setMethod("neutralLoss", "Spectra", "NLParam")` to simply calculate precursor m/z - fragment m/z
- `setMethod("neutralLoss", "Spectra", "HNLParam")` to calculate the hypothetical neutral loss spectra
- `setMethod("neutralLoss", "Spectra", "FragmentParam")` allowing to define the neutral loss fragment (to accommodate the `PSMatch` approach?)

**Comment by michaelwitting** [comment]
The one I had in mind is `precursor m/z - fragment m/z`, but if we have the others as well that would be great.

**Comment by jorainer** [comment]
Working on it.
