### ISSUE TITLE
To extract method info from mzXML file(s)?

### ISSUE THREAD

**Issue by linlennypinawa** [rformassspectrometry/Spectra#253]
It is not waste of time to dive into details about the data quality.    

While exploring TIC, BPC, EIC's chromatogram and spectra, I had questions about dwell time, hplc column type/name/dimention, mobile phase A/B, and so on.

I wonder if a mzXML file stores such information, and if we could extract them?

**Comment by jorainer** [comment]
AFAIK mzXML allows only to store a limited number of things. The successor (mzML) is much more flexible and expandable. Some things like TIC or LC pressure are already stored in there. What can be extracted depends what the [mzR](https://github.com/sneumann/mzR) package supports. That package is used by almost every R package importing data from mzXML, CDF and mzML files.
