### ISSUE TITLE
Implement (internal or virtual?) backend with *compressed* DataFrame 

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#26]
In addition to the `MsBackendDataFrame` it might be useful to implement also a `MsBackendRleDataFrame` backend that *compresses* columns by converting their content to `Rle`. This behaviour is currently implemented in the `MsBackendMzR` but might be useful also for other backends (such as for a Hdf5-based backend that keeps spectra variables in memory while storing the peaks matrices into a hdf5 file).

**Comment by lgatto** [comment]
Note that there are *compressed* versions of many `S4Vector` sub-classes (that are not `Rle`), so I would argue against calling it *compressed*.

I am still of the opinion that it would be easier to implement the behaviour in the `MsBackendDataFrame` as default (possibly with an option to avoid it).

**Comment by jorainer** [comment]
No objection to have it in the `MsBackendDataFrame`. Eventually by having also a slot `@useRle` that, if `TRUE` compresses columns by default and if `FALSE` does not do that. Each accessor function will then have to either directly return the column value or first uncompress it. Would that be OK?

**Comment by lgatto** [comment]
I think this complicates the code (each accessor needs to check the `@useRle` slot) - that is essentially the same as having two classes, `MsBackendDataFrame` and `MsBackendRleDataFrame`. I would go for making an executive decision, to use `Rle`s. If the user doesn't like it, they should be able to change it back:
```r
> x <- DataFrame(x = 1, y = letters, z = rep(1, 2))
> x
DataFrame with 26 rows and 3 columns
            x           y         z
    <numeric> <character> <numeric>
1           1           a         1
2           1           b         1
3           1           c         1
4           1           d         1
5           1           e         1
...       ...         ...       ...
22          1           v         1
23          1           w         1
24          1           x         1
25          1           y         1
26          1           z         1
> x$x
 [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
> x$x <- Rle(x$x)
> x
DataFrame with 26 rows and 3 columns
        x           y         z
    <Rle> <character> <numeric>
1       1           a         1
2       1           b         1
3       1           c         1
4       1           d         1
5       1           e         1
...   ...         ...       ...
22      1           v         1
23      1           w         1
24      1           x         1
25      1           y         1
26      1           z         1
> x$x
numeric-Rle of length 26 with 1 run
  Lengths: 26
  Values :  1
> x$x <- as.numeric(x$x)
> x
DataFrame with 26 rows and 3 columns
            x           y         z
    <numeric> <character> <numeric>
1           1           a         1
2           1           b         1
3           1           c         1
4           1           d         1
5           1           e         1
...       ...         ...       ...
22          1           v         1
23          1           w         1
24          1           x         1
25          1           y         1
26          1           z         1
```
Or is there something more under the hood?

**Comment by jorainer** [comment]
well, currently this is done automatically by the accessor/setter functions (see https://github.com/rformassspectrometry/Spectra/blob/jomaster/R/MsBackendMzR-functions.R#L70-L146 for the helper functions and https://github.com/rformassspectrometry/Spectra/blob/jomaster/R/MsBackendMzR.R#L111-L123 for a getter/setter using these). 

The user is not expected to manipulate/change the data type of the columns - the `$<-` method is also converting columns automatically to Rle - and *un-Rle* them when retrieving (see https://github.com/rformassspectrometry/Spectra/blob/jomaster/R/MsBackendMzR.R#L375-L386).

I'm fine with using the `Rle`-conversion in `MsBackendDataFrame` by default.

**Comment by sgibb** [comment]
I am against an `@useRle` slot, too. Using `Rle` internal as default should be fine. I would also vote to return `Rle` in the accessor methods. If the user really want a classic vector it is easy enough to call `as.numeric` or even `as.vector` (we could show that in the vignette/man pages). In general `Rle` works out of the box for most operations without conversion to a simple vector (e.g. `Rle >= x`).

**Comment by jorainer** [comment]
I am against returning `Rle`s in the accessor methods. We have to make a clear definition of the interface where we e.g. say `msLevel` returns `integer`, not `msLevel` might return an `integer` or an `Rle` with `integer` if ... Note that `Rle` is nice, but not thought to be used if you don't have any longer runs in your data. Also, most *standard* users can handle base R data types, but will get confused if they are exposed to things lile `Rle`.

I would just use `Rle` internally just for the `DataFrame`-based backends. Other backends like database-based ones will not use `Rle` at all.
