### ISSUE TITLE
Externalize hdf5 backend?

### ISSUE THREAD

**Issue by meowcat** [rformassspectrometry/Spectra#264]
Hi,

the MsBackendHdf5 obviously carries rhdf5 as a dependency. This makes build times quite long on Linux, when using Spectra in a docker. Could it be considered to move it to a separate package like other backends?

**Comment by meowcat** [comment]
Forget it. There's tons of other things that also take long :D

**Comment by jorainer** [comment]
hm - it also puzzles me a bit; what docker container are you using? if you used the bioconductor/bioconductor_docker:devel (or maybe also with the :RELEASE_3_16) then binary linux packages would be available and nothing would needed to be compiled?

**Comment by meowcat** [comment]
We were using another one, but now back to bioconductor devel.
