### ISSUE TITLE
Rename fileNames to dataSource

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#28]
Use `dataSource` instead of `fileNames` and use `fromDataSource` instead of `fromFile`.

**Comment by lgatto** [comment]
Other suggestions for the new name would be `dataStore` and `fromDataStore`

**Comment by jorainer** [comment]
I have a slight tendendy on `dataSource` over `dataStore` - mostly because of the term store being used in e.g. app store and similar. But I can live with both options. @sgibb , what would you prefer?

**Comment by sgibb** [comment]
For me `source` and `store` (I like `storage` more) are different things. 
- For an in-memory backend: `source` is the mzML file and `storage` would be in-memory.
- For an HDF backend: `source ` is the mzML file and `storage` would be the HDF files.
- For an mzML backend: `source` and `storage` would point to the same file.

So what about `storage` (or `dataStorage` or `dataLocation`) for the *storage* of the data (e.g. HDF file, database, ...) and `source` (or `dataSource`, or `origin`) for the *source* file (mostly mzML; would replace the `@fromFile` slot). E.g. in our first implementation of the HDF backend the `@hdffiles` slot had to be of the same length as the `@fromFile` slot. This would limit us to a file-based approach. Allowing different *storages* for the same *source* file (e.g. split a mzML file into two HDF files) would increase the flexibility for parallelisation etc. (see also #30).

IMHO both accessors `dataSource` (`dataOrigin`) and `dataStorage`  (`dataLocation`) would be useful.

**Comment by lgatto** [comment]
:100: points for the distinction between *source* (`dataSource`) and *storage* (`dataStorage`) - I think this will save lots of headache.

**Comment by jorainer** [comment]
OK, so you propose to use `dataStorage` to define where the **current** data gets from, i.e. when you call `mz` where are these values retrieved from (which would be `NA` for memory, the mzML file for mzR backend and the Hdf5 file for the hdf5 backend).

`dataSource` would then be from where the data originates (actually, I would prefer `dataOrigin` in that case). Now I'm not quite sure if we want this to be a *core* spectra variable, do we?

**Comment by lgatto** [comment]
It's actually important to record where the data comes from.

Does it hurt to have these as _core_ variables? It would be much space, especially as an Rle.

**Comment by jorainer** [comment]
Doesn't hurt, no.

So we would have two new accessors:
- `dataStorage` returns `character`
- `dataOrigin` returns `character`

that OK?
