### ISSUE TITLE
Add a filterPrecursorIsotopes method

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#281]
Add a `filterPrecursorIsotopes` method that reduces a `Spectra` keeping only spectra with a precursor m/z representing monoisotopic masses, i.e. group spectra in the input `Spectra` using the `MetaboCoreUtils::isotopologues` function on their precursor m/z and keep for each group only the one with the lowest m/z.

**Comment by AharoniLab** [comment]
Are #281 and #280 on their way to be merged into ?

**Comment by jorainer** [comment]
not yet. We need to make a PR for these first.

**Comment by AharoniLab** [comment]
I can upload/share a small DIA-HRMS test spectra if that would be helpful.

**Comment by jorainer** [comment]
What puzzles me now is how such `Spectra` with MS2 spectra from isotope-ions can be generated. Maybe we should discuss that again @AharoniLab
