### ISSUE TITLE
Add modCount and files as spectra variables

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#30]
Instead of having dedicated `@files` and `@modCount` slots in the backend we could also add this as spectra variables. Advantages:
- modifications on a per-spectrum basis possible.
- subsetting would be (much) easier.

Disadvantages:
- memory demand might be larger - depending on backend.
- validator methods for file-based backends might be a little slower because they have to extract first the unique source names.

**Comment by jorainer** [comment]
Having the `dataSource` as `Rle` (or also `factor`) in the spectra data is IMO no difference than having it as an `integer` in the spectra data and as a `@dataSource` slot. In fact it makes more sense to have `dataSource` as a core spectra variables in contrast to `fromFile`.

Each backend needs to put different constraints on this variable. The hdf5 and mzR backends will have to make sure that these data sources in fact exist, while e.g. for a data base backend even differen data sources could be used (e.g. spectra from HMDB, or MoNa or MassBank).

For the `modCounter` I am still not completely convinced if that would make sense having it as a core spectrum variable. @sgibb , can you try to convince me on that?

**Comment by sgibb** [comment]
I think `dataSource` is a core spectra variable and having it in the `DataFrame` would be allow easier subsetting as you pointed out. 

The current implementation has a `@fromFile` and  `@modCounter` that are equal in length. While `spectra_apply` (and similar functions that change the spectra) accept an user-defined splitting factor for parallelisation the current implementation is limited on a file based approach because the `@modCounter` has to be incremented (and the length must be identical to `@fromFile`). So currently we can just split by file or not at all. While this makes somehow sense for mzML files and the organisation/parallelisation of an HDF file/database could be very different and you may want to split the parallelisation in a finer grade. In that case it would be useful to have a modification counter for each spectrum. By the way that is very similar to your very first implementation of the HDF backend with a md5 checksum for each spectrum.

Also a spectrum-based modification counter could be useful to find out which spectra have changed after an operation, e.g. after  `removePeaks(x, t < 1e2)` we could see which spectra are modified (we could also provide a log output `"peaks removed in 42/1024 spectra"`.

**Comment by jorainer** [comment]
Note: parallelization *per-se* is not limited by `@modCounter` or `@files`/`fromFile`. You can use `mz`, `intensity`, `peaks` with whatever parallelization/splitting factor `f` you want (and the lazy processing queue will be applied accordingly). What is limited is when it comes to **apply** the changes (make them permanent). For that I think it makes sense to do it on a per file level only. Concurrent write access in an Hdf5 file is for example not possible. Also, SQLite does not allow parallel insert/update calls.

The idea of the per-spectrum mod counter is nice, I would that. **But** I don't think it is worth the effort to check for each spectrum if a method such as `remove_peaks` actually changed the peaks matrix or not. Unless you find an efficient way to implement this I would go with the current *all-or-nothing* approach: if you write/apply changes, apply them to all and increment the mod counter of all.

I'm still not very convinced of having the `modCounter` as a *core* spectrum variable. I still think this is something related to the backend and the way the data is stored and is not really related to the spectrum data (which would then be something like a logging mechanism for individual spectra - but I would rather not want to have that to keep things as simple (and fast) as possible).

**Comment by lgatto** [comment]
Re the spectrum level `modCount` and parallel processing needs, what about this use case: 
> I want a backend where spectra a stored in their own respective files because their processing is the most time consuming operation and they are always processed independently anyway.

**Comment by jorainer** [comment]
The question is if they really *need* to be in their own files or if it would be possible to load them into memory. I you have a `MsBackendDataFrame` you can do the parallelization as you like, with any partitioning of the spectra.

If they need to be in their own files it's also simple enough with the `MsBackendHdf5`:
- split the `Spectra` by e.g. individual spectrum.
- change the backend from whatever backend you have to a `MsBackendHdf5` 
- 

So all this is possible already - and is IMHO independent of the `modCount`.

I think we all agree on the `dataStorage` to be a core spectrum variable.

The `modCount` is a different story, and this really depends on its definition: we initially added this variable to be able to check if the data **within the data storage** had changed, i.e. if two backends point to the same HDF5 files (which is possible) and for one of the two the peak data was changed and this was written to the HDF5 file, this would also change the peak data for the other backend. So, we throw an error if the `modCount` in the backend (for a certain file) differs from the one within the file. For that use case I think we should keep the `modCount` as its own slot in the `MsBackend` and don't add it as spectra variable.

The `@modCount` slot was not intended to keep track of changes of peak data of a single spectrum. This would be sort of a logging mechanism for spectrum objects and would indeed be an spectrum variable.

So, summarizing, I would:
- Add the `dataLocation` as a spectra variable and drop the `@files` slot.
- Keep the `@modCount` slot (on a per-`dataLocation` basis) as it is now as a property of the backend, not the spectrum.

**Comment by jorainer** [comment]
Update on:

> The current implementation has a @fromFile and @modCounter that are equal in length. While spectra_apply (and similar functions that change the spectra) accept an user-defined splitting factor for parallelisation the current implementation is limited on a file based approach because the @modCounter has to be incremented (and the length must be identical to @fromFile). So currently we can just split by file or not at all. 

That's not correct:

```r
> library(Spectra)
> fl <- dir(system.file("proteomics", package = "msdata"), full.names = TRUE)
> sps_tmt <- Spectra(backendInitialize(MsBackendMzR(), files = fl[5]))
> sps_tmt <- removePeaks(sps_tmt, t = 5000)
> peaks(sps_tmt)
List of length 509
> peaks(sps_tmt, f = msLevel(sps_tmt))
List of length 509
> peaks(sps_tmt, f = seq_along(sps_tmt))
List of length 509
```

All work.
