### ISSUE TITLE
Smoothing along the time domain (chromatographic peaks)

### ISSUE THREAD

**Issue by breidan** [rformassspectrometry/Spectra#316]
Hi,
I admit I am a bit behind the curve because I only recently began using the functionalities of `Spectra`. 

So far I did this kind of smoothing with `MSnbase::combineSpectraMovingWindow` by loading individual files and writing them back to mzML after smoothing. Then I would load all files into a `XCMSnExp` object and proceed with processing.

Is there a simpler, maybe more efficient way with `Spectra` and the other packages of rforMassspectrometry? I see that there is the `combineSpectra` function, could that be used for this purpose, and if so, how?

Thanks.

**Comment by jorainer** [comment]
actually, no, we did not implement the `combineSpectraMovingWindow` yet in `Spectra` et al. I'm not sure when we will find the time to implement this (also because the current code is not directly applicable to the new data structures), so you're save using it.
