### ISSUE TITLE
Visualize, use plotSpectraMirror function to draw spectrum matching results

### ISSUE THREAD

**Issue by v-v1150n** [rformassspectrometry/Spectra#319]
I have now completed the Spectra match and got the results. 
Now I want to use the `plotSpectraMirror` function to plot all these compounds, but I am not sure how to check that these matched spectra correspond to the two **msps file**. 
The index value of the file content. Is there any way I can find the respective index value?
The following is the content of my file

```
> summary(sample_msp)
 Length   Class    Mode 
    373 Spectra      S4 

> summary(mona_spec_libno)
 Length   Class    Mode 
  18915 Spectra      S4 

> mtch_mona
Object of class MatchedSpectra 
Total number of matches: 7 
Number of query objects: 373 (7 matched)
Number of target objects: 18915 (2 matched)
```

**Comment by jorainer** [comment]
I'm closing this issue and answer in the duplicated issue at https://github.com/sneumann/xcms/issues/744
