### ISSUE TITLE
travis ci

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/Spectra#36]
I added a `.travis.yml`. Currently `Spectra` doesn't check without errors. If it would build without errors we will need to work on the deploy part (personal access token and testing).

**Comment by jorainer** [comment]
I'm on it to fix the master branch...

**Comment by jorainer** [comment]
master branch is OK now.

**Comment by sgibb** [comment]
Still failing. There is a problem with the data files from `msdata`:
https://travis-ci.org/rformassspectrometry/Spectra/jobs/549473991#L1286-L1295
```
── 1. Failure: initializeBackend,MsBackendMzR works (@test_MsBackendMzR.R#10)  ─
unique(be$dataStorage) not equal to `fl`.
2/2 mismatches
x[1]: "/home/travis/R/Library/msdata/sciex/20171016_POOL_POS_1_105-134.mzML"
y[1]: "/tmp/RtmpiRcWtP/RLIBS_3c243ba3a194/msdata/sciex/20171016_POOL_POS_1_105-1
y[1]: 34.mzML"
x[2]: "/home/travis/R/Library/msdata/sciex/20171016_POOL_POS_3_105-134.mzML"
y[2]: "/tmp/RtmpiRcWtP/RLIBS_3c243ba3a194/msdata/sciex/20171016_POOL_POS_3_105-1
y[2]: 34.mzML"
```
That may be because of the caching mechanism at travis.

**Comment by jorainer** [comment]
I guess it's mostly because internally we are using `normalizePath` on file names - I've added `normalizePath` also to the reference files names in the unit tests now.

**Comment by jorainer** [comment]
Seems to work now (https://travis-ci.org/rformassspectrometry/Spectra)

**Comment by jorainer** [comment]
Or at least we pass *Build* now...

**Comment by sgibb** [comment]
That was just a temporary connection issue. It pass now!
We still need to test the deploy part (for the vignette) that is just activated for the master branch. I guess we have to wait until #43 has been merged.

**Comment by lgatto** [comment]
The package site on the gh-pages branch is now active and accessible.
