### ISSUE TITLE
What is the unit for rtime? Minutes or seconds?

### ISSUE THREAD

**Issue by cpanse** [rformassspectrometry/Spectra#37]
https://github.com/rformassspectrometry/Spectra/blob/984cbdb1c840061bbafa91ea236ed2ec24c3c0d3/R/MsBackend.R#L269

**Comment by jorainer** [comment]
its seconds.

**Comment by lgatto** [comment]
It's actually in the units available in the data - we don't convert manually. For a display in minutes, there `formatRt`.

**Comment by jorainer** [comment]
as far as I remember the CPP code in `mzR` that extracts the data using proteowizard (or proteowizard itself) converts it to seconds by default. But in R we don't convert as Laurent said

**Comment by cpanse** [comment]
thanks; should be added to the man page.
