### ISSUE TITLE
change filterPrecursorMz to accept an m/z range

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#57]
The current implementation of `filterPrecursorMz` has parameters `mz` and `ppm` both being a `numeric(1)`. This is however different from the way `filterMz` is used (i.e. takes an `m/z` of length 2) which I find confusing.

I'd propose to change `filterPrecursorMz` to take also an `mz` being a `numeric(2)` defining the lower and upper m/z boundary and removing the `ppm` parameter alltogether.

Any comments @lgatto @sgibb ?

**Comment by lgatto** [comment]
Yes for consistency.

I have one thought though. Setting the range by hand as you suggest is more convenient, but this range isn't equivalent throughout the whole m/z range (this [question](https://www.biostars.org/p/8453/) summarises my thoughts). Using an m/z of `length` 2 wouldn't necessary be ideal to filter specific peaks at very different m/z. Or may be it doesn't matter that much?

**Comment by jorainer** [comment]
I'm a little confused by the thoughts you expressed. 
Regarding the `ppm`, I thought you use a relative accuracy like that because TOF MS are less accurate for higher masses but I could be mistaken here.

> Using an m/z of length 2 wouldn't necessary be ideal to filter specific peaks at very different m/z. 

Why? If you provide `mz = c(123.2, 123.3)` you would get all spectra with a precursor m/z within that range - if you would want to use a single m/z with a ppm of 10 you could do `mz = 123.2 + ppm(c(-123.3, 123.2), 10)`. 

What would not be possible (but that was also not possible before) was to filter for multiple m/z simultaneously, i.e. get all spectra that have a precursor m/z of 123.3 **or** 123.6 **or** 343.2 with a **single** `filterPrecursorMz` call.

**Comment by lgatto** [comment]
I was referring to a case where one would want to filter out a peak at a low and a high m/z range. `mz = 123.2 + ppm(c(-123.3, 123.2), 10)` solves it, thanks.

**Comment by jorainer** [comment]
I will add this also as an example.
