### ISSUE TITLE
Replace peaks method by as.list

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#62]
Replace the `peaks` method by `as.list` (see https://github.com/rformassspectrometry/RforMassSpectrometry/issues/14).

**Comment by jorainer** [comment]
Here we run into a problem: replacing `peaks` by `as.list` would be OK, but we have also a `peaks<-` method that allows to replace the m/z and intensity values. I think it would be crucial to have a dedicated method to replace the m/z-intensity **pairs**, especially because `mz<-` or `intensity<-` would not work because they would have to be called sequentially with the first potentially leaving the data in an invalid state (e.g. because replacing m/z values first will result in a different number of m/z and intensity values).

I would thus propose to add a `mzIntensityPairs` and `mzIntensityPairs<-` method (replacing the `peaks` method) and making a symlink from `as.list` to `mzIntensityPairs`. I know, the name is pretty ugly, but we could then have the analogues in `Chromatograms`: `rtimeIntensityPairs` and `rtimeIntensityPairs<-`.

What do you think @lgatto @sgibb ?

**Comment by sgibb** [comment]
Or `replaceList` (in analogy to `S4Vectors::replaceCOLS`/`S4Vectors::replaceROWS`) or `list2spectra`/`list2chromatograms` (in analogy to `base::list2env`/`base::list2DF`)?

Or we define our own `as.list<-` operator (`as.list(object) <- value`)

**Comment by jorainer** [comment]
Excellent idea @sgibb! I like the `replaceList<-`! (I find the `as.list<-` a little unintuitive).

**Comment by lgatto** [comment]
Ok, that seem sensible to me.
