### ISSUE TITLE
Add some basic plotting functions

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/Spectra#80]
In the "ms proteomics" user/developer session we discussed some `plot` functions.

We want to:
- use only *base graphics* (no `ggplot2`, no `lattice`, ...).
- use unit tests with `vdiffr`.
- keep it simple and basic (no annotation, no ion mobility).

Initial planned functions:
- `plot(Spectra[1])` plots a single spectrum (as `type = "l"` for profile (default) and `type = "h" for centroided).
- `plot(Spectra[1:10])` plots multiple spectra above each other as stacked plot or as *messy*/coplot plot all in the same plot area.
- `lcmsMap(Spectra)`: "3D" plot, rt on the x-axis, mz on the y-axis, intensity colour-coded.

(hand-crafted image is following)

![IMG_1566](https://user-images.githubusercontent.com/5506112/70623715-fdbf7100-1c1e-11ea-8dc9-9009a68323de.JPG)

See example stub code:
https://github.com/rformassspectrometry/Spectra/blob/bca663197cb18471d92613a9b4417d9b9f3adeb8/R/plot-functions.R#L1-L26

CC: @cpanse, @tobiasko

Please have a look at the [plot branch](https://github.com/rformassspectrometry/Spectra/tree/plot).

**Comment by tobiasko** [comment]
Cool! Regrading unit testing. I guess you already saw this @sgibb , but just in case...Accoiding to [stackoverflow](https://stackoverflow.com/a/44990728) [vdiffr](https://github.com/r-lib/vdiffr) is used by gglot for unit testing.

**Comment by sgibb** [comment]
Thanks @tobiasko, I already add a small unit test for the very basic `.plotSingleSpectrum` function:
https://github.com/rformassspectrometry/Spectra/blob/ad405ee94f59e02c9ac7b0582c8dd7ef7b29cbe5/tests/testthat/test_plot-functions.R#L13-L25

**Comment by tobiasko** [comment]
Maybe a stupid question, but why do `Spectra::mz(...)` and `Spectra::intensity(...)` return a list instead of a vector, also for `length(Spectra) == 1` ? Connected, my naive  `.plotSingleSpectrum(...)` would use the getter functions  also internally:
```
## Create a Spectra providing a `DataFrame` containing the spectrum data.
spd <- DataFrame(msLevel = c(1L, 2L), rtime = c(1.1, 1.2))
spd$mz <- list(c(100, 103.2, 104.3, 106.5), c(45.6, 120.4, 190.2))
spd$intensity <- list(c(200, 400, 34.2, 17), c(12.3, 15.2, 6.8))
s <- Spectra(spd)

#plot single spectrum 
plot(x = unlist(mz(s[1])), y = unlist(intensity(s[1])), type="h")
```
Isn't that easier to read than
```
v <- as.list(x[1L])[[1L]]
    plot(x = v[, "mz"], y = v[, "intensity"], type = type,
         xlab = xlab, ylab = ylab, ...)
```
? Especially without `unlist(...)` boiling down to ```plot(x = mz(s[1]), y = intensity(s[1]), type="h")```

**Comment by tobiasko** [comment]
What about a ```stopifnot(class(x) == "Spectra")``` as first line in `.plotSingleSpectrum`?

```
tobi <- function(x){
  stopifnot(class(x) == "Spectra")
  plot(x = unlist(mz(x[1])), y = unlist(intensity(x[1])), type="h")
}
```
gives

```
> tobi("abc")
 Show Traceback
 
 Rerun with Debug
 Error in tobi("abc") : class(x) == "Spectra" is not TRUE 
```

**Comment by sgibb** [comment]
1. `as.list` because all backend classes return a `list` of matrices if you extract the data (at least the mzML and HDF-based ones so we kept this). In general we don't want to handle special cases. So the users/developers never need to check for the length of a `Spectra` object, e.g. `if (length(Spectra) > 1) mz(Spectra)[[1]] else mz(Spectra)`. That is the same for `mz`, `intensity`, `as.list`, ... (you have the same behaviour in base R, e.g. `strsplit`).

2. The internal `.plot*` functions should be as lightweight as possible because they would be called multiple times. Also we don't need to check for `is(x, "Spectra")` because we would provide a S4 method latter that calls this internal function and than R is doing the method dispatching based on the class type. (BTW: `stopifnot(class(x) == "Spectra"))` and `is(x "Spectra")` would fail if you inherit from `Spectra` (e.g. the today mentioned `ThermoSpectra` class); `inherits(x, "Spectra")` would be the way to go.)

**Comment by tobiasko** [comment]
Minor comment:

`is(x, "Spectra")` would not fail if x is an instance of a class that inherits from `Spectra`.

```
> setClass("Person", 
+          slots = c(
+            name = "character", 
+            age = "numeric"
+          ), 
+          prototype = list(
+            name = NA_character_,
+            age = NA_real_
+          )
+ )
> 
> setClass("Employee", 
+          contains = "Person", 
+          slots = c(
+            boss = "Person"
+          ),
+          prototype = list(
+            boss = new("Person")
+          )
+ )
> 
> me <- new("Employee", name = "Tobias")
> is(me, "Person")
[1] TRUE
> 
```

because `is(x)` returns a list of all inherited classes:

```
> is(me)
[1] "Employee" "Person"
``` 
See also help page of inherits(...):

"The analogue of inherits for formal classes is is. The two functions behave consistently with one exception: S4 classes can have conditional inheritance, with an explicit test. In this case, is will test the condition, but inherits ignores all conditional superclasses."

I guess this means that inherits(...) should not be used for S4 objects?

**Comment by sgibb** [comment]
@tobiasko thanks for this hint, I wasn't aware of that. From reading `?inherits` you indeed right that `inherits` is an "S3" method that doesn't catch all possible edge-cases. `is` was introduced with "S4" and should be used.

**Comment by tobiasko** [comment]
Sorry, again a comment regarding `as.list(...)`. I know you can find this type of naming in base R...but I think it violates the [bioc coding style](https://bioconductor.org/developers/how-to/coding-style/) for function names:

Function names

Use camelCaps: initial lower case, then alternate case between words.
**Do not use ‘.’ (in the S3 class system, some(x) where x is class A will dispatch to some.A).**
Prefix non-exported functions with a ‘.’.

I also don't really get the idea behind the naming. The name suggests a datatype conversion function for a primitive data type like

```
> as.list("abcd")
[[1]]
[1] "abcd"
```
but [as.list](https://github.com/rformassspectrometry/Spectra/blob/plot/R/Spectra.R#L940) is actually a accessor method for a S4 class. Don't you think this creates confusion when looking at the code?

**Comment by tobiasko** [comment]
...maybe something like `toList(...)` would be better, although I still feel that it is hard to guess what the function actually returns, because it only cares about the m/z and intensity slots, right?

**Comment by sgibb** [comment]
I moved your API question to #86 to keep this issue clean for discussions about the plotting functions itself.

**Comment by lgatto** [comment]
@jorainer @sgibb - what do you think of putting all the plotting/visualisation functionality into their own package?

**Comment by sgibb** [comment]
@lgatto sounds good, especially if anybody wants to use `ggplot2` which will attach a lot of dependencies. I like the `mlr3` (Machine Learning for R) packages, where you have a specific package for each task/use case: 

![](https://raw.githubusercontent.com/mlr-org/mlr3/master/man/figures/mlr3verse.svg?sanitize=true)

**Comment by jorainer** [comment]
I'm principally OK with that. Originally I've planned to have base R graphics plots in `Spectra` and `ggplot2`-based ones in a separate package.

**Comment by jorainer** [comment]
What I would however not like is to mix base R plots and ggplot in the same *plotting* package...

**Comment by lgatto** [comment]
Ok, so this seems to be a welcome initiative. What about naming :-)

- `MsVis` or (the Americanised version) `MsViz`. This one is general, but might be more appropriate for a meta package, that would serve as a gateway for base, ggplot2 and interactive plotting.
- Simply `MsPlotting`
- `ggms` for a ggplot2-based package 
- ...

**Comment by jorainer** [comment]
I would suggest the following:
- have base R plots directly in `Spectra`. They would not add much of dependencies.
- have `ggspectra` and `ggchromatograms` for `ggplot2`-based plots - separate for the two packages, because if you're just working with spectral data there is no need to install and load also the `Chromatograms` package.

**Comment by sgibb** [comment]
This issue was for basic plotting functions. These are implemented (missing the LCMS-MAP).
