### ISSUE TITLE
Dropping spectra variables/columns containing only NA values

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#81]
Importing mzML files can result in many columns that contain only `NA` values. While it is possible to use `selectSpectraVariables` to manually select columns (to keep) it would also be convenient to have a function such as `na.omit` or `dropNA` that removes all columns that contain only `NA` values.

We could then also have a parameter in the constructor function that would remove that.

**Comment by jorainer** [comment]
Implement `dropNaSpectraVariables` function.

**Comment by jorainer** [comment]
Or better `dropNAspectraVariables`?

**Comment by jorainer** [comment]
Or `dropEmptySpectraVariables`??? from how it reads that's my favorite at present - any opinion @lgatto @sgibb ?

**Comment by sgibb** [comment]
`dropEmptySpectraVariables` or `dropNonInformativeSpectraVariables` (could remove `NA` and columns where every value is identical, e.g. if all spectra have the same polarity but we have to ensure that some columns are preserved even if they are all identical e.g. `msLevel`), e.g. from `topdownr`:
https://github.com/sgibb/topdownr/blob/76327b084a4008cbec81edb1a02cbfa259f561a7/R/functions-data.frame.R#L67-L86
```r
#' Drop NA only columns (all rows are NA)
#'
#' @param x `data.frame`/`DataFrame`
#' @return x, without columns that are NA
#' @noRd
.dropNaColumns <- function(x) {
    keep <- !.vapply1l(x, function(xx)all(is.na(xx)))
    x[, keep, drop=FALSE]
}


#' Drop non informative columns (all rows are identical)
#'
#' @param x `data.frame`/`DataFrame`
#' @param keep `character` column names that should never be dropped.
#' @return x, without columns that are identical
#' @noRd
.dropNonInformativeColumns <- function(x, keep="Mz") {
    keep <- !.vapply1l(x, .allIdentical) | colnames(x) %in% keep
    x[, keep, drop=FALSE]
}
```

**Comment by jorainer** [comment]
I would actually keep it as simple as possible - thus I would not like to remove *non informative* spectra variables. `centroided`, `msLevel`, `polarity` are still informative, even if they are all the same value. But, since you have already a `dropNaColumns`, would you like to implement that @sgibb ?

**Comment by sgibb** [comment]
Feel free to copy it (I don't want to write the documentation :stuck_out_tongue_winking_eye: but I guarantee a sympathetically review).
