### ISSUE TITLE
[API] Rename `as.list`?

### ISSUE THREAD

**Issue by sgibb** [rformassspectrometry/Spectra#86]
Converted from #80:
Sorry, again a comment regarding `as.list(...)`. I know you can find this type of naming in base R...but I think it violates the [bioc coding style](https://bioconductor.org/developers/how-to/coding-style/) for function names:

Function names

Use camelCaps: initial lower case, then alternate case between words.
**Do not use ‘.’ (in the S3 class system, some(x) where x is class A will dispatch to some.A).**
Prefix non-exported functions with a ‘.’.

I also don't really get the idea behind the naming. The name suggests a datatype conversion function for a primitive data type like

```r
> as.list("abcd")
[[1]]
[1] "abcd"
```

but [as.list](https://github.com/rformassspectrometry/Spectra/blob/plot/R/Spectra.R#L940) is actually an accessor method for a S4 class. Don't you think this creates confusion when looking at the code?

...maybe something like `toList(...)` would be better, although I still feel that it is hard to guess what the function actually returns, because it only cares about the m/z and intensity slots, right?

_Originally posted by @tobiasko in https://github.com/rformassspectrometry/Spectra/issues/80#issuecomment-565099906_

**Comment by sgibb** [comment]
We are happy to find better names for our functions. So any suggestion is highly welcomed. 

We already had some discussion about this function in the past and just changed it name recently to `as.list`: #62 

Just to provide you some background why we named the function `as.list`:

- It was `peaks` before (that's the name of the corresponding function in `mzR` and `MSnbase`). We saw problems with naming clashes in `Spectra::peaks`, `Chromatogram::peaks` and `MsExperiment::peaks`. Also `peaks` isn't a useful name for "profile" spectra neither for chromatogram data.
- While `as.list` indeed violates [our](https://rformassspectrometry.github.io/RforMassSpectrometry/articles/RforMassSpectrometry.html#coding-style) and [bioconductor's](https://bioconductor.org/developers/how-to/coding-style/) coding style it is a well known function from base R and should be supported by us. `as.list`/`as.vector/...` are supported by many bioconductor packages/classes like `S4Vectors` (e.g. `as.list.Rle`, `as.vector.Rle`).
- It does exactly what it supposed to do: turning a `Spectra` object into a `list` (where each element is a spectrum as `matrix`, this `matrix` could maybe be larger than n*2 (mz/intensity) in the future for different backends, but I currently see no point in adding an additional dimension). So in our interpretation it is not an accessor but an converter.

IMHO `toList` is more or less the same but replaces a well known base function (`as.list`) with a unknown alternative.

**Comment by tobiasko** [comment]
@sgibb I think a better name would be `getPeakList(...)` or `extractPeakList(...)` and this goes back to formats like the mascot generic format (mgf) that use the following notation:

```
EGIN IONS
TITLE=Spectrum 2
PEPMASS=1084.9
SCANS=3
RTINSECONDS=25
345.10 237
370.20 128
460.20 108
.
.
.
1673.30 1007
1674.00 974
1675.30 79
END IONS
```

The central part is the ion/peak list following

`position intensity`

btw. even in these early times  people where already thinking about extension. The third field is actually reserved for the charge state of a peak, see [mgf](http://www.matrixscience.com/help/data_file_help.html). So the generalised format is

`position intensity PeakAttribute1 PeakAttribute2 PeakAttribute3 ...`

As shown on our poster and during the developer day, orbitrap analyzers already write more attributes to arrays (centroid mode). We get ` position intensity noise resolution charge`. Future instruments might add additional attributes like mobility etc. I would therefore opt to be prepared and to return an `Array`or lists of `Array` that can cope with any additional dim.

**Comment by tobiasko** [comment]
Regarding:

> * It was `peaks` before (that's the name of the corresponding function in `mzR` and `MSnbase`). We saw problems with naming clashes in `Spectra::peaks`, `Chromatogram::peaks` and `MsExperiment::peaks`. Also `peaks` isn't a useful name for "profile" spectra neither for chromatogram data.

@sgibb What is the idea behind `Chromatogram::peaks` and `MSExperiment::peaks`? You were planing to have a `peaks(...)` function that take `Chromatogram` or `MsExperiment` as parameters? What would these functions do?

**Comment by jorainer** [comment]
The discussion was also already in https://github.com/rformassspectrometry/Chromatograms/pull/8#pullrequestreview-282344717

Originally we had the `peaks` method to return this `list` of peak matrices. Then I was implementing the `Chromatograms` package and there you have essentially the same thing: a method that returns a `list` of matrices, only with `rtime`-`intensity` pairs instead of `mz`-`intensity` pairs. My initial idea was to call that method `pairs` - but we were not happy with that and after looooong discussions we ended up with `as.list`. And the `as.list,Spectra` returns a `list` of matrices with `mz` and `intensity` values, the `as.list,Chromatograms` a `list` with matrices with `rtime` and `intensity` values.

If you find a better name for these duplets in chromatographic data I would be more than happy. One advantage (and actually the main reason) for `as.list` was that we have a single function for a user to extract the *main* data from the object (`mz`-`intensity` for spectral and `rtime`-`intensity` for chromatographic data).

**Comment by tobiasko** [comment]
For the `Chromatogram` class the function returns a chromatographic trace (int ~ rt), so I would call it something like `extractChromTrace(...)`, but since our detectors are mass analysers a more specific name might be `extractMassTrace(...)`.

**Comment by tobiasko** [comment]
🤔  ...I kind of get your idea behind `as.list(...)` and the wish to be as generic as possible, but `as.list(S4object)` tells you little about the function purpose apart from a type conversion. Imagine `as.list(car)`. What would you guess it returns?  Maybe a nested list where all slot values have been placed in? Your way of using `as.list(Spectra)` corresponds  to `as.list(car)` returning  information on the cars engine, because it is the central component...but a car is a complex object. So why not use `engine(car)` instead? The meaning is perfectly clear without looking at the help page of `engine(...)`.
Going back to as.list(`Spectra`), one could as well expect to get back a list of names or IDs. There is many attributes in a `Spectra` object apart from the peak lists.

**Comment by tobiasko** [comment]
Something related to which data formats might be best suited for spectrum representation in more than 2D:
```
Hi Skyline-daily Users,
I have just released Skyline-daily 19.1.1.309, with, we believe, some really great improvements you will want:

    Our first beta release of support for diaPASEF! (thanks to Brian, Matt, and me)
        We have run this with 2 separate 3-organism datasets through the LFQBench statistical assessment and that works.
        This was a big effort which started for Brian and Matt in April and culminated in a major performance drive which should benefit all proteomewide DIA in Skyline.
        A critical realization wat that sparse IMS spectra are best represented as 3-arrays (m/z, IMS, intensity), and we now plan to move to this representation for Agilent and Waters in the very near future. (stay tuned)
        Parallel file import with proteomewide DIA in the UI or by default on the command-line has performance similar to what was previously only available from the command-line using --import-process-count. Choose "Many" on your next import or just ignore threading the next time you import from the command-line.

```

**Comment by jorainer** [comment]
Regarding the `as.list` discussion: what about a method `spectraList` to extract the m/z-intensity values (spectra) as a `list` of matrices (`spectraList<-` to replace them). For `Chromatograms` we could have `chromList`.

Regarding the `array`. We *should* be save for possible expansions/addition of extra dimensions. We provide the `mz` and `intensity` methods to extract these values and it would be straight forward to add an additional variable/method later. How they are represented and stored will not be defined in the `Spectra` class, but the backend class(es).

**Comment by jorainer** [comment]
Picking up the discussion again as we should get to a solution. I would propose:

1) keep `as.list` and `replaceList`.

2) change to `asList` and `replaceList<-`.

Using the word *list* here keeps the function generic enough (I think) to support later to return also a list of `matrix` with more columns than *just* m/z and intensity.

Please use a thumbs-up for 1), thumbs-down for 2) or suggest an alternative.

@sgibb @lgatto @tobiasko

**Comment by lgatto** [comment]
Here are my thoughts, that are based on the type of audience (user or developer) and backend (read-only or writeable) - both being linked. 

- When it comes to user, a function defined in the API to extract the spectra as a list is required. To me, `as.list` and `as(, "list")` are obvious choices, that could possibly be overloaded with another function. 

- I am not sure we need to define a replacement function in the API, that would only be relevant for backends that support writing anyway. Most of the cases will involve on-the-flight processing. 

- For the backends with write access, wouldn't it be better (safer) to provide an `updateSpectra` function that takes a `Spectra` object as input and a function that will update/modify the data in a specify way. This would be a general way for users to process their data, in addition to the functionality we already propose. The extreme case would be something like 
```r
updateSpectra(x, function(xx, myListOfSpectra) xx <- myListOfSpectra[name(xx)])
```
