### ISSUE TITLE
General design questions

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/Spectra#9]
Some general implementation/design questions:

1) Do we enforce `names` on the spectra like we have it in `MSnbase`?
2) Naming conventions for `MsBackend` implementations?

**Comment by jorainer** [comment]
Re 1) : currently I would go for the option to *not* require (unique) names on the spectra, since not all backends might provide such ids. If we go for names, I think we should not enforce a rigid naming scheme on them.

**Comment by lgatto** [comment]
As far as I can see, the only reason names were important was to assure a match between spectra and their feature data. This indeed doesn't make much sense anymore, given that different backends can end up with very different implementations. I agree that we shouldn't enforce any at this stage.

**Comment by lgatto** [comment]
Re 2), I am wondering if we should use more explanatory names for these backends. For example, there is now a `MsBackendMemory` backend, which is indeed *in memory* but also uses a `DataFrame` to encode the data. So this backend could also be called `MsBackendDataFrame` or `MsBackendMemoryDataFrame`. This is getting very long indeed, but may it would be useful to have a way to know more about a backend without looking in its code.

I see two possibilities, other than having long names:
1. we add a `description` slot with a brief textual description (could also be an element in a `metadata` list)
2. each backend has its own man page (currently not the case)
3. we briefly document each backend in the `MsBackend` man page

I like 1 and 3. 

We also need a way to find all available backends, which 3 would also solve. See also [issue 428 in `MSnbase`](https://github.com/lgatto/MSnbase/issues/428)

What do you think @sgibb @jorainer?

**Comment by jorainer** [comment]
I'd go for 3. Most users will not be really interested in much details of a backend, so a small section for each backend should do it. I do not really like 1, as I would rather want to separate documentation and code/implementetion.

Re name, I'm OK with renaming to `MsBackendDataFrame`.
