### ISSUE TITLE
Backends for the meta-data

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/Spectra#93]
This issue is the reason I opened #92 in the first place. 

When reading many raw data files (504 in our specific case here in the lab), creating the `spectraData` data can become prohibitive. When looking a little by closer, it transpires that it's not really the size of the data at the end (`Total_RAM_Used` below) that is the immediate point of failure, but the size of the data while it's being created (`Peak_RAM_Used`). 

![RAM_usage](https://user-images.githubusercontent.com/384198/75985723-11f8ce80-5eed-11ea-931c-d92b8e14c547.png)

I can see two options
1. Optimise the [code](https://github.com/rformassspectrometry/Spectra/blob/master/R/MsBackendMzR.R#L54-L59) that creates the `spectraData` in `backendInitialize,MsBackendMzR`:
2. Create a backend for on disk metadata.

I think it's reasonable to consider option 2, even if for our specific problem, we could *simply* more to a computer with more RAM.

My questions to @sgibb and @jorainer:
1. What do you think of options 1 and 2 here?
2. Would we want two independent backends, one for the raw data (as we have) and one for the metadata, or back-ends that deal with both?
3. What about giving `SQLite` a go for the meta-data?

There is of course much more to discuss, but this is a start. 

Cc @plantton

**Comment by jorainer** [comment]
Some thoughts on that:

- Is there a difference if you use `register(SerialParam())` before running the test above? Could be that the `bplapply` does some additional copying...
- I could imagine that the `cbind` call causes copying of the `data.frame`. It could be that adding an additional column using `$` (or `[[`) does not cause copying... could be an easy first shot.
- The idea of a backend that uses a SQLite-based metadata sounds good to me. This makes indeed sense to me, as subsetting, filtering and searching would all be possible using SQL calls - and that should be very efficient.

Possible change to use the `$` instead of the `cbind` in [code](https://github.com/rformassspectrometry/Spectra/blob/master/R/MsBackendMzR.R#L54-L59) could be:

```r
spectraData <- do.call(
    rbind, bplapply(files,
                              FUN = function(fl) {
                                  tmp <- Spectra:::.mzR_header(fl)
                                  tmp$dataStorage <- fl
                                  tmp
                              }, BPPARAM = BPPARAM))
```

**Comment by lgatto** [comment]
It tested the `$`, comparing the default `cbind` implementation to 
```
backendInitialize_MsBackendMzR <-
    function(object, files, ..., BPPARAM = bpparam()) {
        if (missing(files) || !length(files))
            stop("Parameter 'files' is mandatory for 'MsBackendMzR'")
        if (!is.character(files))
            stop("Parameter 'files' is expected to be a character vector",
                 " with the files names from where data should be",
                 " imported")
        files <- normalizePath(files)
        msg <- Spectra:::.valid_ms_backend_files_exist(files)
        if (length(msg))
            stop(msg)
        spectraData <- do.call(
            rbind, bplapply(files,
                            FUN = function(fl) {
                                tmp <- Spectra:::.mzR_header(fl)
                                tmp$dataStorage <- fl
                                tmp
                            }, BPPARAM = BPPARAM))              
        spectraData$dataOrigin <- spectraData$dataStorage
        object@spectraData <- spectraData
        validObject(object)
        object
    }
```
with
```
basename(f <- msdata::proteomics(pattern  = "20141210", full.names = TRUE))
n <- c(1, 10, 20, 40, 80, 150)

for (i in seq_along(n)) {
    fls  <-  rep(f, n[i])
    res1[[i]] <- peakRAM(b1 <- Spectra::backendInitialize(MsBackendMzR(), files = fls))
    res2[[i]] <- peakRAM(b2 <- Spectra:::backendInitialize_MsBackendMzR(MsBackendMzR(), files = fls))
    stopifnot(identical(b1, b2))
}
```
There doesn't seem to be any difference
![bench](https://user-images.githubusercontent.com/384198/76161153-b6b71e00-6130-11ea-8153-e6ae7f4fdb4b.png)
Note that this was run using the default `MulticoreParam()`,

**Comment by lgatto** [comment]
However, a major issue with using SQLite is that we loose all the `S4Vectors` functionality, and the possibility to have lists of S4 objects as columns... unless it is possible to store blobs in SQLite. @jorainer, do you know it that possible?

**Comment by lgatto** [comment]
Here are two potential candidates for such metadata backend:
- [SQLDataFrame](https://bioconductor.org/packages/release/bioc/html/SQLDataFrame.html)
- [DelayedDataFrame](https://bioconductor.org/packages/release/bioc/html/DelayedDataFrame.html)

**Comment by jorainer** [comment]
Regarding blobs: yes, that's possible with SQLite (fast and easy too).

**Comment by lgatto** [comment]
See https://github.com/RforMassSpectrometry/MsBackendSql
